# Generated by Django 5.1.7 on 2025-05-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0008_remove_trip_public_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="deleted_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="tripjoinrequest",
            name="deleted_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="tripjoinrequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="tripparticipant",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="tripparticipant",
            name="deleted_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="tripparticipant",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="tripuserrelation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="tripuserrelation",
            name="deleted_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="tripuserrelation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="trip",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
